pages/features/ai-agents.mdx
=> patch: fix 404 link

pages/beta-preview/active-features/live-document-sync.mdx, pages/changelog/_meta.json, pages/changelog/overview.mdx, pages/changelog/v1.5.9.mdx, pages/index.css, theme.config.tsx
=> 1.5.9 changelog + local document sync

pages/changelog/_meta.json, pages/changelog/v1.5.11.mdx, theme.config.tsx
resolves https://github.com/Mintplex-Labs/anything-llm/issues/1881
Release log for 1.5.11
=> v1.5.11 changelog

pages/changelog/_meta.json, pages/changelog/v1.6.1.mdx, theme.config.tsx
=> 1.6.0 changelog

pages/agent/setup.mdx
[AnythingLLM PR](https://github.com/Mintplex-Labs/anything-llm/pull/2223)
Added SearchApi to Search Providers
=> Add SearchApi to search providers

pages/beta-preview/active-features/live-document-sync.mdx
=> Fixing typos in Update live-document-sync.mdx

pages/llm-not-using-my-docs.mdx
Typo fix in docs: is -> as
resolves #xxx
=> Minor docs typo fix: llm-not-using-my-docs.mdx

pages/installation-desktop/overview.mdx
fixes https://github.com/Mintplex-Labs/anythingllm-docs/issues/106
Links for desktop installation were 404-ing. This PR fixes the path for all such links
=> fix(docs): broken links in installation docs

pages/fine-tuning/overview.mdx
Added fine tuning cost (since it isn't listed anywhere else)
resolves #xxx
Added pricing info for fine-tuning, since it doesn't seem to be documented anywhere
=> Update overview.mdx with fine-tuning pricing

pages/fine-tuning/cloud-fine-tuning.mdx
The initial  sentence was not properly phrased as it had some grammatical issues.
resolves #xxx
=> Rephrased the sentence

pages/installation-desktop/storage.mdx
=> 129-Windows data location typo

pages/changelog/_meta.json, pages/changelog/v1.7.4.mdx, pages/changelog/v1.7.5.mdx
=> 1.7.5 changelog

pages/nvidia-nims/system-requirements.mdx
No Related Issue.
Provide more context around Nvidia's limitations to remove confusion. 
This is only documentation change.
=> Update NIM system requirements to provide more information. 

pages/agent/usage.mdx
=> Spelling correction

pages/features/all-features.mdx
Changed the href for the System Prompt Variables card on the features page from absolute path to relative path.
The System Prompt Variables card incorrectly routed using an absolute path. This card now properly routes using relative path like other cards on the page.
Other cards on the features page were checked for valid routing.
=> fixed href path for system-prompt-variables

pages/agent-not-using-tools.mdx
=> fixed typos

pages/configuration.mdx
resolves #xxx
- Add docs for disabling streaming for generic OpenAI provider via env
=> Disable generic OpenAI streaming via env

pages/installation-docker/available-images.mdx
Update "built use" to "built to use"
- [x ] 🐛 fix
- [x ] Ensured updated documentation pass spell check
- [ x] Updated or added relevant links as needed
- [x ] Reviewed the changes for clarity and accuracy
- [ x] Successfully ran the code locally without encountering errors
=> fix: improve spelling/grammar

pages/introduction.mdx
resolves #189 
Adds Marcello Fitton to the Mintplex Labs team members list on the introduction page.
=> add Marcello Fitton to the team list in introduction.mdx

pages/configuration.mdx
Docs for PR https://github.com/Mintplex-Labs/anything-llm/pull/4394 for Simple SSO login-disabled homepage redirect
=> Add support for `SIMPLE_SSO_NO_LOGIN_REDIRECT` for Simple SSO config

pages/_meta.json
resolves #194
Adds title field to "community-hub" page in `_meta.json`
Screenshot:
=> Add title for Community Hub in _meta.json
